# Site Settings
title: The Mystery Project
email: baker_street@yeah.net
description: 追寻未知, 探求真相.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bakerstreet221abc.github.io" # the base hostname & protocol for your site
google_analytics: "UA-124253568-1"

# User Settings
username: The Mystery Project
user_description: 追寻未知, 探求真相.
disqus_username: disqus_jEsAeOuABa

# Social Media
# Remove the item if you don't need it
# github_username: github_username
# facebook_username: facebook_username
# twitter_username: twitter_username
# instagram_username: instagram_username
# linkedin_username: linkedin_username
# medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: 首页
    url: /
  - title: 关于The Mystery Project
    url: /about/
  - title: 加入我们
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
